### ISSUE TITLE
Error :-( 

### ISSUE THREAD

**Issue by efraim-il** [nicknem/supertinder#13]
Hello :-) 

I have updated the facebook ID and the auth required but I still get an error when I try to run it, any chance you can help me understand why? 

root@kali:~/supertinder# ruby tinder.rb
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- watir-webdriver (LoadError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from tinder.rb:6:in `<main>'

Edit (!): After searching forever on the net I have managed to solve those error above. 
(Had to run:  gem install watir-webdriver -v 0.9.1 

At first, I tried to get my facebook ID and auth from those 2 links. 
[this ](http://findmyfbid.com/) and [this ](http://stackoverflow.com/questions/11237610/how-to-get-a-facebook-access-token-for-a-page-with-no-app-or-app-secret) but I guess they were useless because Charles is 100% accurate and the results were absolutely different. 
(Those website told me that my facebook ID is 127069***0 and my auth key is  257857091296384|hTcWi18Jty_3msA5a****NpVjok)

After some time I read that I need to get those from Charles. Managed to get those and updated supertinder. Then I gave premissions with chmod +x tiber.rb then typed ruby tinder.rb in terminal.

Then It loads but does not work... 
I can see: 

Welcome to SuperTinder
########################
52*cd2*a6cf1*6*e64000e54 (edited some of it with asterisks only because I post it here) 
I hit enter, it shows this one:
97abd6cb-**ac-***e-b962-6f9332b95fd5

Then I hit another enter, and it says "something went wrong"  Why is that? :-( 

Help would be appreciated :)

**Comment by efraim-il** [comment]
Just sniffed again and discovered I probably had an error. Instead of using the information on the top I used those below... Here's a picture.
 
![charles](https://cloud.githubusercontent.com/assets/21081295/21337366/3ec90f10-c675-11e6-9e08-c497689ca0b5.PNG)

Updated it but I get the same error when I try to run it. 

![screenshot from 2016-12-19 22-40-05](https://cloud.githubusercontent.com/assets/21081295/21337663/df6fc6c8-c677-11e6-8edf-5279d3089210.png)
![screenshot from 2016-12-19 22-39-21](https://cloud.githubusercontent.com/assets/21081295/21337664/df8cdc72-c677-11e6-973c-5260eadf634c.png)
![screenshot from 2016-12-19 22-39-23](https://cloud.githubusercontent.com/assets/21081295/21337665/dfa2a818-c677-11e6-80b3-edbd06c9dc94.png)

**Comment by nicknem** [comment]
I can't try it IRL now that I have a girlfriend!

I see that recent changes removed the use for Watir-webdriver. The way I used it is that watir opened a web browser and scraped my fbId and fbAuthToken (if I remember correctly).

Here's how it was done: 
```
# Tinder API		 +puts "Paste in your Facebook ID:"
 -base_uri = "https://api.gotinder.com/"		 +fb_token = gets.chomp
 -# -------------		 +puts 'Paste your Facebook Auth Token:'
 -# Login		 +fb_id = gets.chomp
 -# -------------		
 -# Ask for credentials		
 -puts "Type in your Facebook login"		
 -myLogin = gets.chomp		
 -		
 -# Get facebook password without displaying it		
 -puts 'Type your Facebook password'		
 -myPassword = STDIN.noecho(&:gets)		
 -		
 -puts '==== FACEBOOK ===='		
 -puts 'Fetching Facebook data...'		
 -		
 -browser = Watir::Browser.new		
 -puts 'Fetching your Facebook token'		
 -		
 -# Webdriver		
 -browser.goto 'https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token'		
 -browser.text_field(:id => 'email').when_present.set myLogin		
 -browser.text_field(:id => 'pass').when_present.set myPassword		
 -# browser.button(:name => 'login').when_present.click		
 -fb_token = /#access_token=(.*)&expires_in/.match(browser.url).captures[0]		
 -puts 'My FB_TOKEN is '+fb_token		
 -		
 -puts 'Fetching your Facebook ID...'		
 -# browser.stop		
 -sleep 2		
 -browser.goto'https://www.facebook.com/profile.php'		
 -fb_id = /fbid=(.*)&set/.match(browser.link(:class =>"profilePicThumb").when_present.href).captures[0]		
 -puts 'My FB_ID is '+fb_id		
 -		
 -browser.close
```

Did you try finding your fbId from there: http://findmyfbid.com/

It's either an error with your fbId or your token I'd say. Did you try logging into the functions autolike and list_chicks ?

Maybe @benbristow can help!

**Comment by vegan22** [comment]
Hi man :-) 
I tried from that website, it's the same I got from Charles.  Got the token from Charles as well. 

logging into the function like autolike and list_chick? what? ;-)

**Comment by efraim-il** [comment]
Hi man :-) 
I tried from that website, it's the same I got from Charles.  Got the token from Charles as well. 

logging into the function like autolike and list_chick? what? ;-)

**Comment by nicknem** [comment]
I meant inserting `puts` statements to check if the functions aren't buggy?

I'll give it a try when I have a moment. But try to `puts` the responses you should be receiving from the Twitter API.

**Comment by efraim-il** [comment]
Still I don't really understand you. 
I got another script working but I wonder why this one doesn't work as well ..

Update me if this works for you :)

**Comment by nicknem** [comment]
I'll let you know!

**Comment by efraim-il** [comment]
Thanks

בתאריך יום ה׳, 22 בדצמ׳ 2016, 8:16, מאת Antonin Archer ‏<
notifications@github.com>:

**Comment by efraim-il** [comment]
nicknem? Any news? 
This one (https://gist.github.com/rtt/5a2e0cfa638c938cca59) worked for me but now that I have got tinder plus it stopped working

**Comment by nicknem** [comment]
Hey, no news and I can't really work on this one. My gf won't like it if I spend hours on Tinder haha !
